version = 0.1

[default.deploy.parameters]
stack_name = "fbp-lambda-v3"
resolve_s3 = true
s3_prefix = "fbp-lambda"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# disable_rollback = true
parameter_overrides = "FBPUsersTableName=\"FBPUsers\" FBPScheduleTableName=\"2025-Schedule\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
